name: Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      YANDEX_CLIENT_ID: ""
      API_URL: ""
      TELEGRAM_BOT_LOGIN: ""
      TITLE: ""
      DESCRIPTION: ""
      KEYWORDS: ""
      ACCORDION_JSON: ""
    name: "Build | Lang: ${{ matrix.lang }} | Features: ${{ matrix.features }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - features: ""
            is_wasm: false
            lang: "ru"
          - features: ""
            is_wasm: false
            lang: "en"
          - features: "server"
            is_wasm: false
            lang: "ru"
          - features: "server,chatgpt"
            is_wasm: false
            lang: "ru"
          - features: "server,yandex"
            is_wasm: false
            lang: "ru"
          - features: "server,telegram"
            is_wasm: false
            lang: "ru"
          - features: "server,yandex,telegram"
            is_wasm: false
            lang: "ru"
          - features: "client"
            is_wasm: true
            lang: "ru"
          - features: "client,chatgpt"
            is_wasm: true
            lang: "ru"
          - features: "client,yandex"
            is_wasm: true
            lang: "ru"
          - features: "client,telegram"
            is_wasm: true
            lang: "ru"
          - features: "client,yandex,telegram"
            is_wasm: true
            lang: "ru"
          - features: "client,hydration"
            is_wasm: true
            lang: "ru"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Target Add `wasm32-unknown-unknown`
        if: matrix.is_wasm == true
        run: rustup target add wasm32-unknown-unknown
      - name: Default build
        if: matrix.is_wasm == false
        run: cargo build --no-default-features --features "lang_${{ matrix.lang }},${{ matrix.features }}"
      - name: WASM build
        if: matrix.is_wasm == true
        run: cargo build --no-default-features --features "lang_${{ matrix.lang }},${{ matrix.features }}" --target wasm32-unknown-unknown
